-- Swiggy / Zomato Data Analytics Case Study
-- Database: Oracle SQL
-- Project Type: Food Delivery Data Analysis


-- Section 1: Database Schema Creation

-- Create Users table
CREATE TABLE users (
    user_id       NUMBER PRIMARY KEY,
    name          VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) UNIQUE NOT NULL,
    city          VARCHAR2(50),
    reg_date      DATE DEFAULT SYSDATE
);

-- Create Restaurants table
CREATE TABLE restaurants (
    restaurant_id NUMBER PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    cuisine       VARCHAR2(50),
    city          VARCHAR2(50),
    rating        NUMBER(2, 1)
);

-- Create Orders table
-- Links users and restaurants using foreign keys
CREATE TABLE orders (
    order_id      NUMBER PRIMARY KEY,
    user_id       NUMBER REFERENCES users(user_id),
    restaurant_id NUMBER REFERENCES restaurants(restaurant_id),
    order_date    DATE NOT NULL,
    total_amount  NUMBER(8, 2),
    order_status  VARCHAR2(20) CHECK (order_status IN ('DELIVERED', 'CANCELLED'))
);

-- Create Order Details table
-- Stores individual food items included in each order
CREATE TABLE order_details (
    order_detail_id NUMBER PRIMARY KEY,
    order_id        NUMBER REFERENCES orders(order_id),
    item_name       VARCHAR2(100),
    quantity        NUMBER DEFAULT 1,
    price_per_item  NUMBER(6, 2)
);


-- Section 2: Insert Sample Data

-- Insert Users
INSERT INTO users VALUES (1, 'Rahul Sharma', 'rahul@gmail.com', 'Bangalore', TO_DATE('2023-01-15', 'YYYY-MM-DD'));
INSERT INTO users VALUES (2, 'Priya Patel', 'priya@yahoo.com', 'Mumbai', TO_DATE('2023-02-10', 'YYYY-MM-DD'));
INSERT INTO users VALUES (3, 'Amit Verma', 'amit@gmail.com', 'Bangalore', TO_DATE('2023-03-05', 'YYYY-MM-DD'));
INSERT INTO users VALUES (4, 'Sneha Reddy', 'sneha@outlook.com', 'Hyderabad', TO_DATE('2023-04-20', 'YYYY-MM-DD'));
INSERT INTO users VALUES (5, 'Vikas Gupta', 'vikas@gmail.com', 'Delhi', TO_DATE('2023-05-12', 'YYYY-MM-DD'));


-- Insert Restaurants
INSERT INTO restaurants VALUES (101, 'Truffles', 'American', 'Bangalore', 4.5);
INSERT INTO restaurants VALUES (102, 'Punjab Grill', 'North Indian', 'Mumbai', 4.2);
INSERT INTO restaurants VALUES (103, 'Paradise Biryani', 'Biryani', 'Hyderabad', 4.1);
INSERT INTO restaurants VALUES (104, 'Meghana Foods', 'Biryani', 'Bangalore', 4.6);
INSERT INTO restaurants VALUES (105, 'Bikanervala', 'North Indian', 'Delhi', 3.9);


-- Insert Orders
INSERT INTO orders VALUES (5001, 1, 101, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 450.00, 'DELIVERED');
INSERT INTO orders VALUES (5002, 1, 104, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 700.00, 'DELIVERED');
INSERT INTO orders VALUES (5003, 2, 102, TO_DATE('2024-01-18', 'YYYY-MM-DD'), 1200.00, 'DELIVERED');
INSERT INTO orders VALUES (5004, 3, 101, TO_DATE('2024-02-01', 'YYYY-MM-DD'), 300.00, 'CANCELLED');
INSERT INTO orders VALUES (5005, 4, 103, TO_DATE('2024-02-05', 'YYYY-MM-DD'), 550.00, 'DELIVERED');
INSERT INTO orders VALUES (5006, 1, 104, TO_DATE('2024-02-14', 'YYYY-MM-DD'), 850.00, 'DELIVERED');
INSERT INTO orders VALUES (5007, 5, 105, TO_DATE('2024-02-20', 'YYYY-MM-DD'), 400.00, 'DELIVERED');


-- Insert Order Details
INSERT INTO order_details VALUES (1, 5001, 'Burger', 2, 150.00);
INSERT INTO order_details VALUES (2, 5001, 'Fries', 1, 150.00);
INSERT INTO order_details VALUES (3, 5002, 'Chicken Biryani', 2, 350.00);
INSERT INTO order_details VALUES (4, 5003, 'Paneer Butter Masala', 2, 400.00);
INSERT INTO order_details VALUES (5, 5003, 'Naan', 4, 100.00);
INSERT INTO order_details VALUES (6, 5005, 'Mutton Biryani', 1, 550.00);
INSERT INTO order_details VALUES (7, 5006, 'Special Biryani', 2, 425.00);


-- Save inserted records
COMMIT;


-- Section 3: Business Analysis Queries

-- Query 1: Restaurant-wise Revenue Analysis
-- Calculates total delivered revenue generated by each restaurant
SELECT 
    r.restaurant_id,
    r.name AS restaurant_name,
    NVL(SUM(o.total_amount), 0) AS total_revenue
FROM restaurants r
LEFT JOIN orders o 
    ON r.restaurant_id = o.restaurant_id 
   AND o.order_status = 'DELIVERED'
GROUP BY r.restaurant_id, r.name
ORDER BY total_revenue DESC;


-- Query 2: Users Who Have Never Placed an Order
-- Identifies registered users who have not placed any orders
SELECT 
    u.user_id,
    u.name,
    u.email,
    u.city
FROM users u
LEFT JOIN orders o ON u.user_id = o.user_id
WHERE o.order_id IS NULL;


-- Query 3: Monthly Orders and Revenue
-- Calculates monthly order count and net delivered revenue
SELECT 
    TO_CHAR(order_date, 'YYYY-MM') AS order_month,
    COUNT(order_id) AS total_orders,
    SUM(CASE WHEN order_status = 'DELIVERED' THEN total_amount ELSE 0 END) AS net_revenue
FROM orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM')
ORDER BY order_month ASC;


-- Query 4: Customer Spending Analysis
-- Calculates total orders, total spending, and average order value for each customer
SELECT 
    u.user_id,
    u.name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.total_amount) AS total_spent,
    ROUND(AVG(o.total_amount), 2) AS avg_order_value
FROM users u
JOIN orders o ON u.user_id = o.user_id
WHERE o.order_status = 'DELIVERED'
GROUP BY u.user_id, u.name
HAVING COUNT(o.order_id) >= 1
ORDER BY total_spent DESC;


-- Query 5: Top 3 Restaurants by City
-- Ranks restaurants within each city based on delivered revenue
WITH RestaurantRevenue AS (
    SELECT 
        r.city,
        r.name AS restaurant_name,
        SUM(o.total_amount) AS revenue,
        DENSE_RANK() OVER (
            PARTITION BY r.city 
            ORDER BY SUM(o.total_amount) DESC NULLS LAST
        ) AS rnk
    FROM restaurants r
    LEFT JOIN orders o 
        ON r.restaurant_id = o.restaurant_id 
       AND o.order_status = 'DELIVERED'
    GROUP BY r.city, r.name
)
SELECT city, restaurant_name, NVL(revenue, 0) AS revenue, rnk
FROM RestaurantRevenue
WHERE rnk <= 3;


-- Query 6: Month-over-Month Revenue Growth
-- Compares monthly revenue with the previous month
-- Calculates month-over-month revenue growth percentage
WITH MonthlyRevenue AS (
    SELECT 
        TRUNC(order_date, 'MM') AS month_start,
        SUM(total_amount) AS current_month_revenue
    FROM orders
    WHERE order_status = 'DELIVERED'
    GROUP BY TRUNC(order_date, 'MM')
)
SELECT 
    TO_CHAR(month_start, 'YYYY-MM') AS month_name,
    current_month_revenue,
    LAG(current_month_revenue, 1) OVER (ORDER BY month_start) AS previous_month_revenue,
    ROUND(
        (current_month_revenue - LAG(current_month_revenue, 1) OVER (ORDER BY month_start)) 
        / NULLIF(LAG(current_month_revenue, 1) OVER (ORDER BY month_start), 0) * 100, 2
    ) AS mom_growth_percentage
FROM MonthlyRevenue;


-- Query 7: Customer Cumulative Spending
-- Calculates cumulative spending for each customer over time
SELECT 
    o.user_id,
    u.name,
    o.order_id,
    o.order_date,
    o.total_amount,
    SUM(o.total_amount) OVER (
        PARTITION BY o.user_id 
        ORDER BY o.order_date
    ) AS cumulative_spending
FROM orders o
JOIN users u ON o.user_id = u.user_id
WHERE o.order_status = 'DELIVERED'
ORDER BY o.user_id, o.order_date;


-- Query 8: Best-Selling Item per Restaurant
-- Identifies the most frequently sold food item at each restaurant
WITH RankedItems AS (
    SELECT 
        r.restaurant_id,
        r.name AS restaurant_name,
        od.item_name,
        SUM(od.quantity) AS total_quantity_sold,
        DENSE_RANK() OVER (
            PARTITION BY r.restaurant_id 
            ORDER BY SUM(od.quantity) DESC
        ) AS rnk
    FROM order_details od
    JOIN orders o ON od.order_id = o.order_id
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    WHERE o.order_status = 'DELIVERED'
    GROUP BY r.restaurant_id, r.name, od.item_name
)
SELECT restaurant_id, restaurant_name, item_name, total_quantity_sold
FROM RankedItems
WHERE rnk = 1;


-- Query 9: Cuisine-wise Performance
-- Compares cuisines based on orders, revenue, and average order value
SELECT 
    r.cuisine,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(o.total_amount) AS total_revenue,
    ROUND(AVG(o.total_amount), 2) AS avg_order_value
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
WHERE o.order_status = 'DELIVERED'
GROUP BY r.cuisine
ORDER BY avg_order_value DESC;


-- Query 10: Restaurant Cancellation Rate
-- Calculates total orders, cancelled orders, and cancellation percentage
SELECT 
    r.restaurant_id,
    r.name AS restaurant_name,
    COUNT(o.order_id) AS total_orders_placed,
    COUNT(CASE WHEN o.order_status = 'CANCELLED' THEN 1 END) AS total_cancelled_orders,
    ROUND(
        (COUNT(CASE WHEN o.order_status = 'CANCELLED' THEN 1 END) / NULLIF(COUNT(o.order_id), 0)) * 100, 2
    ) AS cancellation_rate_pct
FROM restaurants r
LEFT JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.name
ORDER BY cancellation_rate_pct DESC;


-- Query 11: Customer Recency Analysis
-- Finds each customer's latest delivered order
-- Calculates the number of days since the last order
SELECT 
    u.user_id,
    u.name,
    MAX(o.order_date) AS last_order_date,
    TRUNC(SYSDATE) - TRUNC(MAX(o.order_date)) AS days_since_last_order
FROM users u
JOIN orders o ON u.user_id = o.user_id
WHERE o.order_status = 'DELIVERED'
GROUP BY u.user_id, u.name
ORDER BY days_since_last_order ASC;



